/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_AUTOMOTIVE_Security_Gateway_PROXY_HPP_
#define V1_AUTOMOTIVE_Security_Gateway_PROXY_HPP_

#include <v1/automotive/SecurityGatewayProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace automotive {

template <typename ... _AttributeExtensions>
class SecurityGatewayProxy
    : virtual public SecurityGateway,
      virtual public SecurityGatewayProxyBase,
      virtual public _AttributeExtensions... {
public:
    SecurityGatewayProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SecurityGatewayProxy();

    typedef SecurityGateway InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls requestSessionKey with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void requestSessionKey(uint32_t _nodeID, uint64_t _nonce, uint64_t _timestamp, std::vector< uint8_t > _publicKey, std::vector< uint8_t > _signature, std::vector< uint8_t > _ecdhPublicKey, CommonAPI::CallStatus &_internalCallStatus, bool &_success, std::vector< uint8_t > &_gatewayPublicKey, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls requestSessionKey with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> requestSessionKeyAsync(const uint32_t &_nodeID, const uint64_t &_nonce, const uint64_t &_timestamp, const std::vector< uint8_t > &_publicKey, const std::vector< uint8_t > &_signature, const std::vector< uint8_t > &_ecdhPublicKey, RequestSessionKeyAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< SecurityGatewayProxyBase> delegate_;
};

typedef SecurityGatewayProxy<> SecurityGatewayProxyDefault;


//
// SecurityGatewayProxy Implementation
//
template <typename ... _AttributeExtensions>
SecurityGatewayProxy<_AttributeExtensions...>::SecurityGatewayProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SecurityGatewayProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SecurityGatewayProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SecurityGatewayProxy<_AttributeExtensions...>::~SecurityGatewayProxy() {
}

template <typename ... _AttributeExtensions>
void SecurityGatewayProxy<_AttributeExtensions...>::requestSessionKey(uint32_t _nodeID, uint64_t _nonce, uint64_t _timestamp, std::vector< uint8_t > _publicKey, std::vector< uint8_t > _signature, std::vector< uint8_t > _ecdhPublicKey, CommonAPI::CallStatus &_internalCallStatus, bool &_success, std::vector< uint8_t > &_gatewayPublicKey, const CommonAPI::CallInfo *_info) {
    delegate_->requestSessionKey(_nodeID, _nonce, _timestamp, _publicKey, _signature, _ecdhPublicKey, _internalCallStatus, _success, _gatewayPublicKey, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SecurityGatewayProxy<_AttributeExtensions...>::requestSessionKeyAsync(const uint32_t &_nodeID, const uint64_t &_nonce, const uint64_t &_timestamp, const std::vector< uint8_t > &_publicKey, const std::vector< uint8_t > &_signature, const std::vector< uint8_t > &_ecdhPublicKey, RequestSessionKeyAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->requestSessionKeyAsync(_nodeID, _nonce, _timestamp, _publicKey, _signature, _ecdhPublicKey, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SecurityGatewayProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SecurityGatewayProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SecurityGatewayProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SecurityGatewayProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SecurityGatewayProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SecurityGatewayProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace automotive
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_AUTOMOTIVE_Security_Gateway_PROXY_HPP_
